apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-to-be-patched
data:
  foo: {{ $.Values.foo }} (from chart template)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-unpatched
data:
  foo: {{ $.Values.foo }} (from chart template)
